- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
https://issues.jboss.org/browse/AEROGEAR-8366
Add GitHub templates from the [aerogear standards](https://github.com/aerogear/standards) to this new repo
Consistent issue and PR templates across aerogear
> Add github templates from the aerogear standards  to the repo

- README.md
- apispec.yaml
https://issues.jboss.org/browse/AEROGEAR-8352
Add Open API documentation for the currently mapped API endpoints
Useful as a reference for anyone on the team to view what is required for each endpoint
Adding yaml spec to the root of the directory with steps to setup swagger-ui locally and view the documentation.
1. Setup Swagger-UI locally
* Option 1: Install the Swagger-UI Chrome extension (https://chrome.google.com/webstore/detail/swagger-ui-console/ljlmonadebogfjabhkppkoohjkjclfai?hl=en)
* Option 2: Using docker. Run `docker run -p 80:8080 swaggerapi/swagger-ui` and `open localhost`
2. Paste https://raw.githubusercontent.com/davidffrench/mobile-security-service-server/AEROGEAR-8352/apispec.yaml in and hit explore
> Add swagger API documention

- .env.example
- .gitignore
- Gopkg.lock
- Gopkg.toml
- cmd/mobile-security-service-server/main.go
- pkg/config/config_test.go
https://issues.jboss.org/browse/AEROGEAR-8389
Add option to use environment variables instead of the defaults from config file.
Configurations can be modified without affecting the checked in codebase.
1. Used [joho/godotenv](https://github.com/joho/godotenv) library
2. Load environment variables in `init()` function in `main.go`
Make a copy of the example `.env` file in the project root:
```sh
cp .env .env.example
```
Modify any value in `.env`. In this example I am going to change the port for the server to run on:
```.env
...
PORT=6000
...
```
Run the server:
```sh
go run cmd/mobile-security-service-server/main.go
```
Check the output from the terminal. It should show that the server is running on port 6000.
```
⇨ http server started on [::]:6000
```
Override the value in `.env` with a …
> [AEROGEAR-8389] Add option to use environment variables

- .gitignore
- Dockerfile
- docker-compose.yml
JIRA: https://issues.jboss.org/browse/AEROGEAR-8395
Created a `Dockerfile` and `docker-compose`.
So that users can run the mobile security server in a container without having to configure an environment.
Copied the `Dockerfile` and `docker-compose` files from [https://github.com/aerogear/aerogear-app-metrics](https://github.com/aerogear/aerogear-app-metrics) and modified to suit this application.
1. Ensure you have `Docker` and `docker-compose` installed and running on your machine.
2. Generate the binary file for the application:
```sh
go build -o mobile-security-service-server cmd/mobile-security-service-server/main.go
```
3. Run the following:
```sh
docker-compose up -d
```
4. Check if your API and database containers are running:
```sh
> docker ps
CONTAINER ID        IMAGE …
```
> AEROGEAR-8395 - Add Dockerfile and Docker Compose file

- Makefile
More efficient docker_release and docker_master make commands
Change the docker_release and docker_master make commands to not build the binary. 
Change the docker_release make command to set the docker latest tag
Needed to ensure binary is not built multiple times by circleci
> fix: Changing docker release and master make commands

- .circleci/config.yml
- Gopkg.lock
- README.md
https://issues.jboss.org/browse/AEROGEAR-8364
Adding CircleCI configuration to this repo
Automatically run tests and docker builds on PRs and tags. 
- Adding a circleci config 
- Creating the repo in circleci, coveralls and dockerhub. Adding the correct env vars
Check the CircleCI job run against this PR passes.
> feat: Add CircleCI configuration

- Gopkg.lock
- cmd/mobile-security-service/main.go
- pkg/models/app_versions.go
- pkg/models/apps.go
- pkg/web/apps/apps_http_handler.go
- pkg/web/apps/apps_http_handler_test.go
- pkg/web/apps/apps_psql_repository.go
- pkg/web/apps/apps_psql_repository_test.go
- pkg/web/apps/apps_service.go
- pkg/web/apps/apps_service_test.go
JIRA: https://issues.jboss.org/browse/AEROGEAR-8349
1. Added an endpoint to get all apps at `/apps`. Created handler, service, model and repository for apps endpoint.
2. Invoked the app handler from `main.go`
We need to retrieve all apps in JSON format to be consumed by a frontend or other service.
Did research to decide on a neat and appropriate design pattern. Created some dummy data as this is not yet connected to a database.
1. Run the application:
```sh
go run cmd/mobile-security-service/main.go
```
Open http://localhost:3000/apps - replace with your own port if you are not using the default value.
You should get the following:
```json
[
{
"id": 1,
"appId": 1,
"appName": "app1",
"numOfDeployedVersions": 0, …
```
> feat(apps-endpoint): added an endpoint to get all apps (AEROGEAR-8349)

- README.md
- api/swagger.yaml
No JIRA
Change the location of api spec and removing disabled and disabledMessage fields from App level
Adhering to Go folder structure by moving swagger spec file to api folder. 
Removing disabled and disabledMessage fields due to change in UI.
Not possible to verify the changes until they are in GitHub :-(
> fix: Change location of api spec and remove fields from App

- Makefile
Noticed that `go errcheck` was being run in `make vet` command and wanted to fix it.
Updated the `make vet` command to run `go vet` instead of `errcheck`.
The wrong command was being run.
1. Change the `GetApps` function in [apps_psql_repository.go
](https://github.com/aerogear/mobile-security-service/blob/master/pkg/web/apps/apps_psql_repository.go#L26) to look like this:
```go
// GetApps retrieves all apps from the database
func (a *appsPostgreSQLRepository) GetApps(c echo.Context) (*[]models.App, error) {
// app1 := models.App{
// 	ID:                    1,
// 	AppID:                 "com.aerogear.app1",
// 	AppName:               "app1",
// 	NumOfDeployedVersions: 1,
// 	NumOfClients:          1,
// 	NumOfAppLaunches: …
```
> fix(makefile): incorrect command was being used in `make vet`

- Makefile
https://issues.jboss.org/browse/AEROGEAR-8519
make setup_githooks   install the errcheck required to git hook for the pre-commit
```shell
go get -u github.com/kisielk/errcheck
```
in order to avoid the issue when tries to commit a change
```shell
.git/hooks/pre-commit: line 12: errcheck: command not found
```
Adding step in the Makefile
Run `$ make setup_githooks` and check that the pkg was installed
```
$ make setup_githooks
Installing errcheck dependence:
go get -u github.com/kisielk/errcheck
Setting up Git hooks:
ln -sf $PWD/.githooks/* $PWD/.git/hooks/
```
Run `$ make setup` and check that the pkg was installed
```
$ make setup
Installing errcheck dependence:
go get -u github.com/kisielk/errcheck
Setting up Git hooks:
ln -sf $PWD/.githooks/* $PWD/.git/hooks/
Installing application …
```
> feat(git-hook): Install errcheck dep when the setup is made (AEROGEAR-8519)

- pkg/httperrors/httperrors.go
- pkg/httperrors/httperrors_test.go
- pkg/models/errors.go
- pkg/web/apps/apps_http_handler.go
- pkg/web/apps/apps_service.go
Our clean architecture separates business logic (filename=service) and delivery (http). We should not be using http errors in the services as multiple delivery methods (http, CLI) would be using the same service file.
Added generic error model that can be used in both the service and repository files. This is then mapped to the http errors which will only be done at the http delivery layer.
Clean separation of responsibilities between our layers. 
All errors in the service and repository layer will return an error using the method `return models.ErrInternalServerError`
None needed in my opinion. Tests are written to cover all cases.
> Adding generic errors and mapping to http errors

- pkg/web/apps/apps_http_handler.go
- pkg/web/apps/apps_psql_repository.go
- pkg/web/apps/apps_psql_repository_test.go
- pkg/web/apps/apps_repository.go
- pkg/web/apps/apps_service.go
- pkg/web/apps/apps_service_test.go
https://issues.jboss.org/browse/AEROGEAR-8522
The Postgres repository interface is tightly coupled to our service layer, this should not be the case. 
The repository layer interface needs to be abstracted away from a specific database implementation. 
Clean separation of concerns
Our Postgres repository file will implement the generic repository interface which is also used in our service.
None required
> fix(apps): Decouple Postgres from service layer (AEROGEAR-8522)

- ui/.eslintrc.json
- ui/package-lock.json
- ui/package.json
- ui/src/App.js
https://issues.jboss.org/browse/AEROGEAR-8505
Add ESLint dependencies
Add config file
Fix some linting problems
Adding more specific standard-react config and related dependencies
See more here: https://github.com/standard/eslint-config-standard-react
See JIRA
Following: https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_linting
I installed VSCode ESLint plugin and ran the comman eslint: Create ESLint configuration
Make some changes which could trigger a linting warning
which are the following:
What I've pushed up is a very basic setup with the https://github.com/standard/standard config enabled. It's possible there might have been some discussion about what we want to go with as a team. Very much open to debate here but would be equally happy to not reinvent the wheel if there …
> adding eslint

- .circleci/config.yml
- Makefile
- README.adoc
https://issues.jboss.org/browse/AEROGEAR-8540
Call the unit tests in the CI
In order to check if all tests are passing to allow the merge
* check if the unit tests and integrations are now been called in the CI
* run locally the command; `make test-all` 
```shell
$ make test-all
Running tests:
GOCACHE=off go test -cover \
github.com/aerogear/mobile-security-service/pkg/config github.com/aerogear/mobile-security-service/pkg/db github.com/aerogear/mobile-security-service/pkg/httperrors github.com/aerogear/mobile-security-service/pkg/test github.com/aerogear/mobile-security-service/pkg/web/apps
ok  	github.com/aerogear/mobile-security-service/pkg/config	0.287s	coverage: 100.0% of statements
?   	github.com/aerogear/mobile-security-service/pkg/db	[no test files]
ok …
```
> feat(tests): Add unit tests to CI

- .circleci/config.yml
- .githooks/pre-commit
- scripts/code-check-install-dep.sh
- scripts/code-check.sh
https://issues.jboss.org/browse/AEROGEAR-8547
Add the code checks that was implemented in the pre-commit to the CI
- It is the only way to ensure that the CI will fail if the errors are found.
- The pre-commit hook can be ignored by `--no-verify`
- centralized actions in the code-check.sh script
- call the script in the CI
- Check if the CI is calling the code-check.sh script and finishes with success
> Add the code checks that was implemented in the pre-commit to the CI

- scripts/commit-filter-check.sh
https://issues.jboss.org/browse/AEROGEAR-8550
CI test which is calling the script code-check-install-dep.sh do not fail when the script fails
To not allow merge PRs which are not passing in the defined rules.
The termination `set -o errexit` is not returning exit as 1 error to CircleCi. The solution here is just to replace it for `exit 1` which will works
1. Locally before this PR/in the current project add a file and try to commit it with a message which will not pass in the script. 
2. Check the error and now commit it with ` --no-verify`
3. Push it to a PR request in the repo and check that all CI tests will be finished with success.
* You can see that exit 1 worked well as expected for other checks. See [here](https://github.com/aerogear/mobile-security-service/pull/46)
* You can try …
> fix(CI) : CI test which is calling the script code-check-install-dep.sh do not fail when the script fails (AEROGEAR-8550)

- .circleci/config.yml
- .gitignore
- api/swagger.yaml
- scripts/check-if-swagger-api-file-is-update.sh
https://issues.jboss.org/browse/AEROGEAR-8541
* Not allow merges with the swagger documentation outdated
* the file in the repo can be used to check it documentation
* for docker image be build with the correct information
* to not allow devs check it outdated when the steps described in the readme to check the swagger api doc locally be executed
* Create a script to verify it and called in the CI
* Commit the changes made in the swagger doc api
* Check if the CI finish with success here 
* Run the script `./scripts/check-if-swagger-api-file-is-update.sh` locally if the `api/swagger.YAML` is not outdated then the script cannot return an error. Otherwise, it needs to return the error. Following an example of how to do make it fails. 
1. Add more one declaration into the apps struct 
2. Run …
> fix(swagger) - Not allow merges with the swagger documentation outdated

- README.adoc
- docker-compose.yml
https://issues.jboss.org/browse/AEROGEAR-8548
Added Swagger container to Docker compose file.
To make it easier to run and view the API documentation.
1. Run `docker-compose up swagger`
2. Go to localhost:8080
3. Is Swagger running at this address?
> feat(swagger): Added a Docker Compose entry for Swagger (AEROGEAR-8548)

- pkg/httperrors/httperrors.go
- pkg/httperrors/httperrors_test.go
https://issues.jboss.org/browse/AEROGEAR-8551
Increased the code coverage for the [`httperrors`](https://github.com/aerogear/mobile-security-service/tree/master/pkg/httperrors) package to 96.2%.
The code coverage was very low (~60%). This needed improvement.
1. Run `go test -cover ./pkg/httperrors`
2. The output should state the code coverage for that package.
```sh
ok      github.com/aerogear/mobile-security-service/pkg/httperrors      (cached)        coverage: 96.2% of statements
```
I could not achieve 100%. This condition could not be entered due to `json.Marshal` being a Go library so I do not have control over this failing.
> fix(unit-tests): Increased code coverage fro httperrors package to 96.2% (AEROGEAR-8551)

- README.adoc
https://issues.jboss.org/browse/AEROGEAR-8561
Links added in the wrong format in the README
Check the fix [here](https://github.com/aerogear/mobile-security-service/blob/626bb79dd724381f755bb60b71c6ee65bcc6bd78/README.adoc)
> fix(readme) : Links added in the wrong format

- pkg/db/db_test.go
https://issues.jboss.org/browse/AEROGEAR-8555
Increased test coverage to 86.7% for the db package.
Code coverage stood at 67% for a critical package. This needed to be increased.
Took the existing testing implementations for this package and converted them to table-driven tests, meaning more cases can easily be added to or removed from each test method.
1. From the root of the project, run the following command to test the `db` package:
```sh
go test ./pkg/db -cover -tags=integration
```
2. Check the output. It should say the code coverage achieved during this test. Did it get 86.7%?
```sh
$ go test ./pkg/db -cover -tags=integration
ok      github.com/aerogear/mobile-security-service/pkg/db      10.030s coverage: 86.7% of …
```
> feat(unit-tests): Increase db package code coverage to 86.7% (AEROGEAR-8555)

- pkg/httperrors/httperrors_test.go
https://issues.jboss.org/browse/AEROGEAR-8568
Added test case to existing test table to cover `models.ErrDatabaseError`.
Test coverage decreased because this new error model was added to a switch statement but the test table for the switch was no updated.
1. Run `go test ./pkg/httperrors -cover`
2. Read the output. Is code coverage at 96.3%?
```sh
ok      github.com/aerogear/mobile-security-service/pkg/httperrors      (cached)        coverage: 96.3% of statements
```
> fix(unit-tests): Added a test case for ErrDatabaseError (AEROGEAR-8568)

- .circleci/config.yml
https://issues.jboss.org/browse/AEROGEAR-8574
- An issue to import echo dep start to show in the CI tests
* The script has been called before the dep are installed. 
* Change the order to call it
Check that the master the swagger.yaml is outdated and it is falling as should be. 
IMPORTANT: has another PR to update the doc. 
PS: This test need be formed before the make build be executed since this command will update the doc and will be not possible do the check
> fix(CI) - script to check if swagger is outdated (AEROGEAR-8574)

- pkg/helpers/db_seed.go
- pkg/helpers/fixtures.go
- pkg/web/apps/apps_psql_repository_test.go
- pkg/web/router/api_test.go
https://issues.jboss.org/browse/AEROGEAR-8581
Make cover test ignore the seed and fixture. This files should not be counted since they do not require unit_tests. 
For when we add new helpers data to be used in the tests the coverage does not decrease
- Create the pkg helpers to keep the fixture and seeds there. In this way, the go test cover can ignore/exclude them since they should not have their own tests 
- Change the references in the imports
- Extract the seed func responsible to create the inserts for its own routine
- Check that the coveralls  increase since it is not checking the new helpers pkg
- All CI should finish successfully
> fix(cover) : Coveralls should not consider the helpers data which are useful for the tests. 

- Makefile
- ui/package.json
https://issues.jboss.org/browse/AEROGEAR-8723
Adding make command to serve the UI
The Go server was not serving the UI
the `make serve` command will set the `STATIC_FILES_DIR` env variable which is required for the Go echo middleware to work correctly. It needs to be the full path to the directory.
1. Run `make serve`
2. Navigate to `http://localhost:3000/`
3. Navigate to `http://localhost:3000/notinghere` and verify it redirects to `http://localhost:3000/`
4. Navigate to `http://localhost:3000/api/apps` and verify the endpoint returns
> feat: Allow UI to be served from Go server (AEROGEAR-8723)

- pkg/web/apps/apps_psql_repository.go
- pkg/web/apps/apps_psql_repository_test.go
- pkg/web/apps/apps_repository.go
- pkg/web/apps/apps_repository_mock_test.go
- pkg/web/apps/apps_service.go
- pkg/web/apps/apps_service_mock_test.go
- pkg/web/apps/apps_service_test.go
https://issues.jboss.org/browse/AEROGEAR-8726
- Implement service and its test which will be called when an app is unbinding
- Implement the repository to update delete_at an app when the unbinding is made and its tests.
This service will be used to unbinding the app by a listener which will be implemented in the future.
- Update the delete_at with the current data
- Check if all unit tests passed
- Check the query manually in a database via pgadmin
1. Run the seed_go to have a database with data
2. Use the query in "DeleteAppByAppID" which follows check the query. 
```sql
UPDATE app
SET deleted_at=$1
WHERE app_id=$2
```
> feat(unbinding) - Implementing unbinding app service and repository (AEROGEAR-8726)

- pkg/helpers/uuid.go
- pkg/web/apps/apps_psql_repository.go
- pkg/web/apps/apps_psql_repository_test.go
- pkg/web/apps/apps_repository.go
- pkg/web/apps/apps_repository_mock_test.go
- pkg/web/apps/apps_service.go
- pkg/web/apps/apps_service_mock_test.go
- pkg/web/apps/apps_service_test.go
https://issues.jboss.org/browse/AEROGEAR-8725
- Implement service and its test which will be called when an app is binding
- Implement the repository to create a new app when the binding is made and its tests.
It will be used when the service is binding in the app. 
1. Check if all unit tests finish with success
2. Check if the queries added are working with success manually in the database.
a) use the seed to insert data in the database
b) use the query in the psql method CreateApp as the following example
```sql
INSERT INTO app (id, app_id, app_name) VALUES ('be2da1f5-a9c4-4305-84bc-80da683fbc36', 'com.aerogear.test', 'test');
```
c) check the query in the psql method UnDeleteAppByAppID as following example.  
```sql
UPDATE app
SET deleted_at=NULL
WHERE app_id='com.aerogear.test'
```
> feat(binding) - Implement binding app service and repository (AEROGEAR-8725)

- ui/src/DataService.js
- ui/src/actions/actions-ui.js
- ui/src/actions/fetch.js
- ui/src/actions/types.js
- ui/src/containers/AppsTableContainer.js
- ui/src/containers/__tests__/AppsTableContainer.test.js
- ui/src/reducers/__tests__/index.test.js
- ui/src/reducers/index.js
https://issues.jboss.org/browse/AEROGEAR-8376
- Added DataService and fetch.js
- Created 3 new reducers to deal with the fetch action, success, failure
- Added boolean state object didfetchfail
- Added logic to render the table on didfetchfail false else render message `unable to fetch apps` - we may want to clean that up to do a nice blank slate experience
Satisfy AC 
See What
_Verify Failed Request on no Db running_
1. Stop the DB if you have it running
2. Run `make serve`
3. Verify that the message `Unable to fetch any apps` is shown
_Verify Failed Request on no returned apps_
1. Run the db using `docker-compose up db` as described [here](https://github.com/aerogear/mobile-security-service#16-running-entire-application-with-docker-compose)
2. Check that there are no records in the db …
> feat: get apps from backend

- scripts/code-check.sh
https://issues.jboss.org/browse/AEROGEAR-8750
Fix script to return an error regards the code format
The CI should return an error when the code is not formatted
Changing the command and using validation for that. 
- Since this PR has not the fix https://github.com/aerogear/mobile-security-service/pull/82 then it should fail in the CI. 
Also, is possible to check if after format it will work as expected.  
- Cherry pick the  https://github.com/aerogear/mobile-security-service/pull/82 to get all fmt
- Then check that the CI will return success after that
OR
*Locally:*
- Execute the `git commit` and see the same msg
- Run `make fmt`
- After fmt the files check that the git commit will finished with success. 
- [] Finished task
> fix(ci): CI not running fmt issues discovered by pre-commit hook - (AEROGEAR-8750)

- api/swagger.yaml
- pkg/web/apps/apps_http_handler.go
- pkg/web/apps/apps_http_handler_test.go
- pkg/web/apps/apps_psql_repository.go
- pkg/web/apps/apps_psql_repository_test.go
- pkg/web/apps/apps_repository.go
- pkg/web/apps/apps_repository_mock_test.go
- pkg/web/apps/apps_service.go
- pkg/web/apps/apps_service_mock_test.go
- pkg/web/apps/apps_service_test.go
- pkg/web/router/router.go
https://issues.jboss.org/browse/AEROGEAR-8742
Renames GetAppsById to GetActiveAppsById
Added `WHERE deleted_at IS NULL` to GetActiveAppsById
Added tests
It is expected behavior that deleted apps don't return from the endpoint
`WHERE deleted_at IS NULL` to GetActiveAppsById
- Run the server and check the following url
```bash
go run cmd/mobile-security-service/main.go
```
Seed the database with
```sql
INSERT INTO app
(id, app_id, app_name, deleted_at)
VALUES 
('1b9e7a5f-af7c-4055-b488-72f2b5f72266', 'com.aerogear.foobar', 'Foobar', NULL),
('ae2da1f5-a9c4-4305-84bc-80da683fbc36', 'com.test.app1', 'App One', '2019-02-18 14:36:35'),
('0890506c-3dd1-43ad-8a09-21a4111a65a6', 'com.aerogear.testapp', 'Test App', NULL);
INSERT INTO version
(id, version, app_id, disabled, disabled_message, …
```
> fix(deleted-at): add deleted_at to sql for GetActiveAppById (AEROGEAR-8742)

- ui/src/containers/AppsTableContainer.js
- ui/src/containers/__tests__/AppsTableContainer.test.js
- ui/src/reducers/__tests__/index.test.js
- ui/src/reducers/index.js
https://issues.jboss.org/browse/AEROGEAR-8552
Clicking on the Table now routes the user to app detailed view passing the id in the route
See Motivation
- Adding the data to the apps state value
- Using the data to pick up the db id of the app using the app name
- pushing a new router to the react router history
_Functionality_
1. Run `make serve`
2. Ensure there are records in the db
3. Navigate to /
4. Click on one of the rows in the table 
5. Verify the id passed in the route matches the app clicked on using data in the database.
_Tests_
1. Run `npm test`
2. expect all tests to pass
> feat: navigate to app on row click

- Makefile
When a new dep is added in the project the `make setup` does not work properly and issues are faced. Then, to solve it is required to remove manually the vendor's dirs. 
Add the fix in the `make clean` command in order to make the it really cleans local env of the project 
Allow the `make setup` works well as expected in the above scenario. 
Run `make clean` and `make setup` and see that all works well as expected. 
Followin the test performed 
```shell
$ make clean
rm -f mobile-security-service
rm -rf .vendor-new
rm -rf vendor/
$ make setup
Installing errcheck dependence:
go get -u github.com/kisielk/errcheck
Setting up Git hooks:
ln -sf $PWD/.githooks/* $PWD/.git/hooks/
Installing application dependencies:
dep ensure
make build_swagger_api
Installing Swagger dep:
go get -u …
```
> fix(make clean) : Remove local vendor dirs

- pkg/web/apps/apps_psql_repository.go
- pkg/web/apps/apps_service.go
https://issues.jboss.org/browse/AEROGEAR-8792
Return empty versions array on /app/:id GET
it was returning "The requested item was not found" when an app existed but did not have any versions.
If an ErrNotFound error is returned from the repository layer, set the deployedVersions on the app model to an empty array.
1. Start the server
2. Seed the database. You can do this with `make test-integration-cover`
3. Hit the endpoint `http://localhost:3000/api/apps/1b9e7a5f-af7c-4055-b488-72f2b5f72266`
4. It should return 
```
{
"id": "1b9e7a5f-af7c-4055-b488-72f2b5f72266",
"appId": "com.aerogear.foobar",
"appName": "Foobar",
"deployedVersions": []
}
```
> fix(apps): Returning empty versions array on app GET (AEROGEAR-8792)

- api/swagger.yaml
- cmd/mobile-security-service/main.go
- pkg/web/apps/apps_http_handler.go
- pkg/web/checks/checks_http_handler.go
- pkg/web/checks/checks_http_handler_test.go
- pkg/web/initclient/init_http_handler.go
- pkg/web/router/api_test.go
- pkg/web/router/router.go
https://issues.jboss.org/browse/AEROGEAR-8797
Add endpoints to return a msg OK when the REST API is running and able to receive requests
* Add endpoints for the livenessProbe and readnessProbe setup
1. Run the app
2. Call this endpoint `http://localhost:3000/api/status` and check if it will return success as expected. 
3. Call this endpoint `http://localhost:3000/api/health` and check if it will return success as expected.
> feat(check) : Add endpoints to check the health of the REST Service API

- Dockerfile
https://issues.jboss.org/browse/AEROGEAR-8796
Fix docker file
Be able to run the service app from it
Add the steps required to get/manage the deps and avoid the following error. 
```
$ oc logs -f bc/mobile-security-service
Cloning "https://github.com/camilamacedo86/mobile-security-service" ...
Commit:	7fb872e9003db0f9e545711944652a7fb7c2414b (Merge pull request #76 from craicoverflow/AEROGEAR-8360)
Author:	Enda <ephelan@redhat.com>
Date:	Mon Mar 11 14:42:03 2019 +0000
Replaced Dockerfile FROM image centos:7
--> FROM openshift/origin-release:golang-1.10 as builder
--> WORKDIR /go/src/github.com/aerogear/mobile-security-service
--> COPY . .
--> RUN go build -o mobile-security-service ./cmd/mobile-security-service/main.go
pkg/models/device.go:3:8: cannot find package "github.com/google/uuid" …
```
> fix(docker) : Fix docker file in order to be able to run the service (AEROGEAR-8796)

- Dockerfile
https://issues.jboss.org/browse/AEROGEAR-8820
Fix docker image to install UI and check it running when a new-app on OCP be created by it
When the project be installed in OCP the UI should works
By adding in the Dockerfile the required steps to install and run the UI
1. Create a project in OCP
2. Create a Postgres from the catalogue with the default values of this project set up in 
3. Run `oc new-app https://github.com/camilamacedo86/mobile-security-service.git#FIX-UI --strategy=docker -e PGHOST=postgresql --name=app`
4. When the deploy finish create the router by `oc expose svc/app`
5. Click on in the router created and check if the UI appears
- [] TODO
> Fix docker image to install UI 

- ui/src/reducers/index.js
https://issues.jboss.org/browse/AEROGEAR-8859
Prevent the table from sorting on a column if every value in that column are equal.
This is expected behaviour. The table should stay the same in this scenario.
Compared all values in column and return the original `rows` array if they are.
1. Try to sort on a table column where all values are the same (if they aren't, change them to be the same).
2. The table state should remain exactly the same.
3. Sort on a column where values are not the same.
4. The sorting order should change.
> fix(table-sorting): Don't sort table if column values are all equal (AEROGEAR-8859)

- ui/src/components/AppDetailedView.css
- ui/src/components/AppDetailedView.js
- ui/src/components/LandingPage.css
- ui/src/components/LandingPage.js
- ui/src/components/Table.css
- ui/src/containers/AppOverviewContainer.css
- ui/src/containers/AppOverviewContainer.js
- ui/src/containers/AppVersionsTableContainer.js
- ui/src/containers/AppsTableContainer.js
- ui/src/containers/TableContainer.css
- ui/src/containers/__tests__/AppOverviewContainer.test.js
- ui/src/containers/__tests__/AppVersionsTableContainer.test.js
- ui/src/containers/__tests__/AppsTableContainer.test.js
- ui/src/index.css
https://issues.jboss.org/browse/AEROGEAR-8850
Create the top level app information as shown on the flat. Also did some additional work to use the [Patternfly 4 Grid Layout](http://patternfly-react.surge.sh/patternfly-4/layouts/grid/). Also added this to the landing page.
To show app information to the user.
1. Go to the app detailed view. For example, http://localhost:3000/apps/0890506c-3dd1-43ad-8a09-21a4111a65a6
2. Does it show the top-level app information above the **Deployed Versions** table?
> feat(ui): Add top-level app information to app detailed view (AEROGEAR-8850)

- pkg/db/db.go
- ui/src/containers/AppVersionsTableContainer.js
https://issues.jboss.org/browse/AEROGEAR-8873
Changed database timestamps to use time zone by default.
To ensure that the timestamp saved has a consistent tim zone with the server (UTC).
1. Drop your database tables:
```sql
DROP TABLE device;
DROP TABLE version;
DROP TABLE app;
```
2. Start the server again:
```go
go run cmd/mobile-security-service/main.go
```
3. Once that is up, seed the database:
```sh
make test-integration
```
4. Change the time zone on your computer. Take note of the difference between your new time zone and UTC (mine is UTC-03, Moncton, Canada).
5. Check the `/apps` endpoint and inspect the values for `deployedVersions[n].lastLaunchedAt` - this should be your old time zone (which is UTC).
6. Go to the …
> feat(db): Changed timestamps to use time zone (AEROGEAR-8873)

- ui/src/components/common/Header.js
https://issues.jboss.org/browse/AEROGEAR-8855
Before, if a user clicked anywhere on the header it would direct them to the homepage. This was changed to ensure they only are directed home when the logo or title text is clicked.
This is expected behaviour.
1. Click the header outside of the text - it should not do anything.
2. Click the title text and it should bring you home.
> feat(header): Only navigate to home on title click (AEROGEAR-8855)

- ui/src/actions/actions-ui.js
- ui/src/components/AppDetailedView.js
- ui/src/containers/NavigationModalContainer.js
- ui/src/containers/__tests__/NavigationModalContainer.test.js
- ui/src/reducers/__tests__/index.test.js
- ui/src/reducers/index.js
https://issues.jboss.org/browse/AEROGEAR-8887
Changing `goBack` to dynamic `targetLocation` so the Navigation modal will work for any react router history location change.
Future proof
Passing target location into Redux from the history block function so it can be used by the navigation modal later on.
1. Checkout this branch locally
2. Modify the isAppDetailedDirty property in the reducer initalState to true
3. Run the server and UI using `make serve`
4. Navigate to the detailed app screen
5. Click the back button in the browser or the header logo
6. Verify the navigation modal appears
7. Verify the X and Stay buttons close the modal and keep you on the same screen
8. Verify the Leave button navigates back to the landing page
PS.: Add images and/or .gifs to illustrate what was changed if …
> fix(ui): Add dynamic targetLocation to NavigationModal (AEROGEAR-8887)

- ui/.env.example
- ui/src/config/config.js
- ui/src/containers/AppVersionsTableContainer.js
https://issues.jboss.org/browse/AEROGEAR-8886
Set a global default value for date format.
To ensure our date format remains consistent and can easily be changed.
Added a new property to config object.
1. Add a new property to your `.env` file:
```env
REACT_APP_DATETIME_FORMAT=YYYY
```
2. Run the application and go the app detailed view. The date columns should only show the year.
3. Remove the property from the `.env` file and it should use the default format defined in `config.js`:
```
YYYY-MM-DD HH:mm:ss
```
> feat(ui): Added global config for date format (AEROGEAR-8886)

- .githooks/pre-commit
- scripts/eslint-check.sh
https://issues.jboss.org/browse/AEROGEAR-8724
Added a script to run ESLint on staged files before committing. If it fails it will block the commit.
To ensure code quality and prevent improper code being committed.
Slightly modified an existing Gist that does this - [linhmtran168/2286aeafe747e78f53bf](https://gist.github.com/linhmtran168/2286aeafe747e78f53bf).
1. Run `make setup_githooks`
2. Alter a JS file to make it fail ESLint (remove a semicolon).
3. Add the file to staging.
4. Try to commit.
5. You should get a fail message, something like this:
```sh
Validating Javascript:
/home/endaphelan/go/src/github.com/aerogear/mobile-security-service/ui/src/components/AppDetailedView.js
29:26  error  Missing semicolon  semi
✖ 1 problem (1 error, 0 warnings)
1 error and 0 warnings potentially …
```
> feat(eslint): Added ESLint script to Git hooks (AEROGEAR-8724)

- .github/PULL_REQUEST_TEMPLATE.md
Present PR template requires you to comment out a lot of suggestion/ placeholder text when filling in your PR 
Ensure that suggestion text in PR template does not render (the text is still visible to act as suggestion text as to what could/ should be included in an area, but just will not render in the final PR text).
When filling in a PR you will now no longer have to delete a bunch of placeholder suggestion text before you add he details of your own PR.
Comment out suggestions/ placeholder text in the PR template
> fix: make pr template suggestions comments

- api/swagger.yaml
- pkg/web/apps/apps_http_handler.go
- pkg/web/apps/apps_http_handler_test.go
- pkg/web/apps/apps_psql_repository.go
- pkg/web/apps/apps_psql_repository_test.go
- pkg/web/apps/apps_repository.go
- pkg/web/apps/apps_repository_mock.go
- pkg/web/apps/apps_service.go
- pkg/web/apps/apps_service_mock.go
- pkg/web/apps/apps_service_test.go
- pkg/web/router/router.go
https://issues.jboss.org/browse/AEROGEAR-8917
- Update the field deleted_at with the current data
- To disable/unbinding the app
- New DELETED endpoint for apps
1. Call the deleted endpoint passing an app which is "active" in the system (E.g `localhost:3000/api/apps/51016c52-7fc6-46ee-b576-38de52622210`)
2. It should return success and the app should no longer be returned into the get all apps
> feat(REST API) : Add DELETE endpoint for apps (AEROGEAR-8917)

- api/swagger.yaml
- pkg/models/app.go
- pkg/web/apps/apps_http_handler.go
- pkg/web/apps/apps_http_handler_test.go
- pkg/web/apps/apps_psql_repository.go
- pkg/web/apps/apps_psql_repository_test.go
- pkg/web/apps/apps_repository.go
- pkg/web/apps/apps_repository_mock.go
- pkg/web/apps/apps_service.go
- pkg/web/apps/apps_service_mock.go
- pkg/web/apps/apps_service_test.go
- pkg/web/router/router.go
https://issues.jboss.org/browse/AEROGEAR-8913
- Create POST endpoint to create app
- Impl QueryParameter into GET endpoint to return the app by appID
- Create PATCH endpoint to update app
- To allow GET and create and update apps using the API
- Attend MDC/Operator requirements
- Create new POST endpoint "/api/apps""
- Add QueryParam "?appId" to the /api/apps GET endpoint
* Call the endpoint `localhost:3000/api/apps` with the following body.
```json
{"appId": "com.aerogear.testpost", "appName": "Test Post" }
```
* Check that the app was created with success
* Call the endpoint `localhost:3000/api/apps` with the following body.
```json
{"appId": "com.aerogear.testpost", "appName": "Test Post New Name" }
```
* Check that the app was updated with success
* Call the the GET endpoint with the …
> (Aerogear 8913) - Rest API changes to allow GET and POST App 

- pkg/models/version.go
`disabledMessage` property should be returned to the client even when empty.
Removed the `omitempty` tag from the `disabledMessage` property.
This property is used client-side to populate a text input, so it is important for tracking the dirty state of the input that the initial value is an empty string instead of `undefined`.
<!-- Add the steps required to check this change. Following an example.
1. View the data from the API for one of the apps at `/api/apps/{id}`. For example: http://localhost:3001/api/apps/0890506c-3dd1-43ad-8a09-21a4111a65a6
2. For this app, ensure at least one of its versions has no value set for the `disabled_message` column in the database.
3. The corresponding app version in `deployedVersions` should have an empty string for the `disabledMessage` property.
> feat(model): Remove 'omitempty' tag (AEROGEAR-XXXX)

- .githooks/commit-msg
- .githooks/pre-commit
- scripts/commit-filter-check.sh
https://issues.jboss.org/browse/AEROGEAR-8888
Extended the commit-msg hook to allow extra types to be defined according to the Conventional Commit specification.
Also I noticed that the `commit-msg` hook was checking previous commits but not the current commit. 
Because of this, the current commit message was passing and getting committed even if the format was incorrect. During the next commit the hook was failing on that previous commit. I changed the script to only look at the content of the current commit message.
Allowed types: _feat, fix, docs, breaking, build, ci, perf, refactor, style, test_
We only had 4 types - docs, feat, fix, breaking. These will probably be used 80% of the time but limiting to these is too restrictive. By adding more we can make our commit messages more …
> ci(commit-msg): Added allowance for extra types in commit message (AEROGEAR-8888)

- api/swagger.yaml
- cmd/mobile-security-service/main.go
- pkg/helpers/fixtures.go
- pkg/models/user.go
- pkg/web/router/api_test.go
- pkg/web/router/router.go
- pkg/web/user/user_http_handler.go
- pkg/web/user/user_http_handler_test.go
JIRA: https://issues.jboss.org/browse/AEROGEAR-9033
Add a endpoint to GET the user which can be used to validate if the user has authenticated with oauth in the UI
Added endpoint to swagger
Added a http_handler for the user resource
Added a service layer for the user resource
Added a model for the user resource
Added the route to the router
1. Run make serve
2. Send a GET request to the user endpoint with the following headers
2.a X-Forwarded-User
2.b X-Forwarded-Email
3. The returned request should be in the following format but with the values you passed
> feat(auth): adding user endpoint to auth against oauth (AEROGEAR-9033)

- ui/src/DataService.js
- ui/src/components/appView/AppOverview.js
- ui/src/components/appView/AppToolbar.js
- ui/src/containers/AppsTableContainer.js
- ui/src/containers/AppsTableContainer.spec.js
https://issues.jboss.org/browse/AEROGEAR-9060
There was an error where the apps view failed to render if no apps were returned from the server. The UI was attempting to perform a `map` on `undefined` which caused the error,
Page failed to load.
A 204 response is returned when no apps exist in the database. For this reason the APPS_FAILURE action was never hit as a 204 is a successful response. I added an additional check in the `DataService` module to return an empty array instead of undefined. This solved the issue.
1. Ensure that the database has 0 apps.
2. Open the UI.
3. You should see `Unable to fetch any apps :/`.
4. Verify tests are passing.
I also fixed some warnings in the browser I noticed that aren't directly related to this PR.
> fix(apps-view): fixed issue where page render failed when no apps were returned from server

- ui/src/DataService.js
https://issues.jboss.org/browse/AEROGEAR-9058
Added a redirect to `/oauth/sign_in` when the response code from a request is either 401 (Unauthorized) or 403 (Forbidden).
To prevent unauthenticated users gaining access to the security service UI. It improves user experience by automatically redirecting users to the login screen.
1. For local testing, temporarily return a 403 from the `GetApps` handler in the API.
```go
// GetApps returns all apps as JSON from the AppService
func (a *httpHandler) GetApps(c echo.Context) error {
return httperrors.Forbidden(c, "")
```
2. Open the homepage of the UI.
3. The page should redirect to `/oauth/sign_in`.
4. Because `/oauth/sign_in` only exists in OpenShift, the URL cannot be resolved and a continuous redirect cycle occurs.
401 is the standard …
> feat(oauth): redirect to login on 401, 403 (AEROGEAR-9058)

- pkg/web/apps/apps_psql_repository.go
https://issues.jboss.org/browse/AEROGEAR-9074
Fix to return correct values for `numOfCurrentInstalls` and `numOfAppLaunches` from `/apps/:id` endpoint
`/apps/:id` endpoint returning `numOfAppLaunches` values for `numOfCurrentInstalls`, and `numOfCurrentInstalls` values for `numOfAppLaunches`
Swap `numOfCurrentInstalls` and `numOfAppLaunches` values
1. Checkout PR branch
2. Run db, server and UI
3. Open main UI view, open app versions view & verify that app versions view has correct values in the `CURRENT INSTALLS` and `LAUNCHES` column (screenshots below)
4. Check api output from `/api/apps` & `/api/apps/<app-id>` & confirm that `numOfCurrentInstalls` and `numOfAppLaunches` values match between api output
UI Before fix:
UI After fix:
> fix(api): returns correct installs and launches values from `/apps/:id` endpoint

- pkg/models/version.go
https://issues.jboss.org/browse/AEROGEAR-9073
stop returning numOfAppLaunches on clientInit endPoint /api/init
is set to zero but should not be returned as can cause developer confusion 
add omitempty to the model
- checkout the branch
- start the go server `make serve`
- run `make test-integration` to test and seed the db
- hit the http://localhost:3000/api/init endpoint with the following body
```json
{  
"appId":"com.aerogear.testapp",
"deviceId":"e71b7790-5537-11e9-88a1-85ea65c9f61e",
"deviceType":"android",
"deviceVersion":"8.0.0",
"version":"0.0.1"
}
``` 
- The response should not contain numOfAppLaunches field e.g.
```json
{
"id": "860fc986-7012-4b00-90f7-fbade5503916",
"version": "0.0.1",
"appId": "io.ionic.starter",
"disabled": true,
"disabledMessage": "The Admin has disabled …
```
> fix(clientInit): stop returning numOfAppLaunches (AEROGEAR-9073)

- ui/src/components/common/CustomAlert/CustomAlert.css
- ui/src/components/common/CustomAlert/CustomAlert.js
- ui/src/components/common/CustomAlert/CustomAlert.spec.js
- ui/src/components/common/TableView.css
- ui/src/containers/AppsTableContainer.js
- ui/src/containers/appView/AppPageContainer.js
- ui/src/containers/appView/AppPageContainer.spec.js
- ui/src/containers/appView/AppVersionsTableContainer.js
- ui/src/index.css
- ui/src/reducers/app.js
- ui/src/reducers/app.spec.js
https://issues.jboss.org/browse/AEROGEAR-9045
Added a Patternfly 4 Alert when an app is successfully saved or when the save failed. 
I wrapped the PF Alert in a custom component, as the PF Alert does not have any props available to control the visibility of the Alert.
To give the user visual feedback when the save has finished.
1. Go to the App Page.
2. Make changes to one of the versions.
3. Click `Save`.
4. You should see an Alert in the top right that reads "Save successful".
5. Click the `x` on the Alert. The Alert should now disappear.
6. Temporarily modify the [`UpdateAppVersions`](https://github.com/aerogear/mobile-security-service/blob/master/pkg/web/apps/apps_http_handler.go#L113) handler in the server to return a Bad Request.
7. Repeat steps **1-3**.
8. You should see an Alert …
> Show an alert when the user saves an app or when the save failed

- .circleci/config.yml
- Dockerfile
- Makefile
Host images on quay.io instead of dockerhub
Host images on quay.io instead of dockerhub
Aerogear images to be hosted on quay.io
Update push command in makefile & add quay.io credentials to project in CircleCI dashboard
- deploy to your local environment
```
minishift start
oc login -u system:admin
make create-all
make create-app
``` 
- update MSS image to point to testing image: `quay.io/damienomurchu/mobile-security-service:c29f31e`
- check that pod redeploys correctly
- check that no functionality has been broken (JIRA [here](https://issues.jboss.org/browse/AEROGEAR-9233) is a good reference as to what to check)
- check that the UI renders the app(s) in the table and the logged in user in the header correctly
> feat(CI): update CI to push images to quay.io instead of dockerhub

- .githooks/commit-msg
- Gopkg.lock
- api/swagger.yaml
- cmd/mobile-security-service/main.go
- pkg/web/router/router.go
- scripts/commit-filter-check.sh
https://issues.jboss.org/browse/INTLY-2458
Expose basic metrics for the Go server from a metrics endpoint
Need to feed them into Prometheus
Using Prometheus Go library and echo for the endpoint
1. Pull this branch down locally
2. Start the server
3. Hit http://localhost:3000/api/metrics 
4. Verify metrics are returned
> feat(metrics): Add prometheus metrics (INTLY-2270)

- Gopkg.lock
- pkg/httperrors/httperrors.go
- pkg/web/middleware/middleware.go
- pkg/web/router/router.go
https://issues.jboss.org/browse/INTLY-2270
Expose HTTP metrics
Need to feed them into Prometheus
Using Prometheus Go library and custom metrics
1. Pull this branch down locally
2. Start the server
3. Hit http://localhost:3000/api/metrics 
4. Verify the following metrics are returned after hitting a few endpoints
- api_requests_duration_seconds
- api_requests_duration_seconds_sum
- api_requests_duration_seconds_count
- api_requests_in_flight
- api_requests_total
5. Modify the /apps handler `GetApps` to always return an error by only having the following line `return httperrors.GetHTTPResponseFromErr(c, err)`
6. Hit the http://localhost:3000/api/apps endpoint a few times
7. Refresh http://localhost:3000/api/metrics 
8. Verify the following is present
- api_requests_failure_total
- [] …
> feat(metrics): Log http metrics (INTLY-2270)

- Makefile
- README.adoc
In going through the project README to install/run the application, I found I couldn't complete all of the steps as outlined. I thought it would be good to fix those steps. (https://issues.jboss.org/browse/AEROGEAR-9480.)
- Added to the README instructions to clarify the current working directory for "make setup".
- Made a change to the Makefile to add the correct path for the swagger executable.
So users can easily complete the steps in future.
By tixing the README and the Makefile.
1. Follow all of the instructions in the README on your machine (machines vary unfortunately).
2. Step 3. (previously 2.) now runs as is because you are in the correct current working directory.
3. Step 3. (previously 2.) now works in setups where there is not already a swagger executable on the PATH (and …
> fix(install): Fixes for local install README and Makefile (AEROGEAR-9480)

- CHANGELOG.MD
- pkg/web/apps/apps_psql_repository.go
- pkg/web/apps/apps_psql_repository_test.go
- pkg/web/apps/apps_service.go
- pkg/web/apps/apps_service_test.go
https://issues.jboss.org/browse/AEROGEAR-9722
This change ensures that the app ID unique constraint is case sensitive.
1. Create an app:
```json
POST http://localhost:3001/api/apps
{
"deviceId": "a2895cc1-28d7-4283-932d-8bcab9e1b566",
"deviceVersion": "3.7",
"version": "2",
"deviceType": "Android",
"appId": "com.aerogear.testapp"
}
```
2. Create another app with same ID but with different cases:
```json
POST http://localhost:3001/api/apps
{
"deviceId": "a2895cc1-28d7-4283-932d-8bcab9e1b566",
"deviceVersion": "3.7",
"version": "2",
"deviceType": "Android",
"appId": "com.aerogear.testapP"
}
```
3. You should get a 409 Conflict error.
```json
{
"message": "Your Item already exists",
"statusCode": 409
}
```
> fix: ensure app ID check is case insensitive.

- .circleci/config.yml
- CHANGELOG.MD
- Makefile
- ui/package-lock.json
- ui/package.json
- Issue faced when the CI is building UI (integrity checksum failed when using sha1:)
- Fix `integrity checksum failed when using sha1:` issue
- Upgrade node and go versions in the CI
> fix(ci) : upgrade node and golang versions

- ui/src/components/appView/AppToolbar.js
- ui/src/containers/appView/AppPageContainer.js
- ui/src/reducers/app.js
- ui/src/reducers/app.spec.js
https://issues.jboss.org/browse/AEROGEAR-9688
Disable the `Disable App` Button when there are no versions related to the app.
Having the button leads the user to the disable app version modal which does nothing when there are no deployed versions associated with the app
added a boolean value to the state which is updated based on the length of the version array when the app is fetched.
1. Create a new app which has no versions associated.
POST to /api/apps
```
{
"appName": "TestApp",
"appId": "com.aerogear.Testapp.Laura.test3"
}
```
2. Verify that the Button is disabled on the app detailed view
3. Simulate a deployment of the app using the /api/init POST
```
{
"deviceId": "a2895cc1-28d7-4283-932d-8bcab9e1b566",
"deviceVersion": "3.7",
"version": "2",
"appName": "TestApp",
"appId": …
```
> fix: disable disable app button on no versions (AEROGEAR-9688)
