- README.md
https://issues.jboss.org/browse/AEROGEAR-8454
Broken links on Readme
Link to contributing and code of conduct are broken in both prerequisites section and contributing section of our Readme
Contributing and Questions section now links to contact section on the aerogear site.
1. Verify license badge is showing on Readme
2. Click contributing guide and verify it links to aerogear community guides 
3. Click AeroGear community and verify it links to aerogear community contact
> Aerogear 8454

- Dockerfile
- docker-compose.yml
Problems building on mac
Adding workaround to build for mac as seen in metrics https://github.com/aerogear/aerogear-app-metrics/blob/master/Dockerfile.rhel7
Couldn't build on mac
Moving build step to the Dockerfile
run `docker-compose up api`
verify the application is running on port 3000
WIP
> WIP build for mac

- .githooks/pre-commit
- Makefile
- README.md
Added a pre-commit Git hook which will format code, check for errors and suspicious constructs before every commit. If any errors are found it will prevent the commit until the committer fixes them.
To ensure the code is error free and well formatted before pushing to remote.
Created a new directory `.githooks` to store the scripts. Added a new `Make` command (`setup_githooks`) to symlink the scripts into your `.git/hooks` directory.
1. Run `make setup_githooks` to set up the hooks.
2. Run `git add . && git commit --amend`.
3. You should see the following output to your terminal:
```sh
$ git add . && git commit --amend
Running pre-commit checks on your code...
```
4. If you see this then the hook is installed correctly and you can exit the commit without saving it.
5. To test if the code …
> feature(git-hook): Added a pre-commit Git hook

- .githooks/commit-msg
adding bash script for checking commit messages to circle ci 
https://issues.jboss.org/browse/AEROGEAR-8465
adding bash script for checking commit messages to circle ci 
to meet with the guide lines outline here
https://github.com/fheng/help/blob/master/development_process.md#commit-messages
adding bash script for checking commit messages to circle ci 
If this PR passes the circle ci build the you can consider it working
to verify locally 
- checkout the branch
- run the script
```
./scripts/commit-filter-check.sh 
```
should get 
```
feat(commit-message-check): remove pwd (AEROGEAR-8465)
'9e58b15b10854dd6e827282e8a2100e529465245' commit message passed
feat(commit-message-check): adding bash script for checking commit …
```
> feat: added brackets to if in githooks (AEROGEAR-8465)

- README.md
https://issues.jboss.org/browse/AEROGEAR-8383
Create a Postgres ERD
To define what tables and fields are needed for our database
Using lucid chart
> feat: Adding ERD to Readme (AEROGEAR-8383)

- Gopkg.lock
- Makefile
- README.adoc
- api/swagger.yaml
- cmd/mobile-security-service/main.go
- pkg/models/apps.go
- pkg/models/versions.go
- pkg/web/apps/apps_http_handler.go
- pkg/web/router/router.go
https://issues.jboss.org/browse/AEROGEAR-8518
Implement changes to generated swagger api doc from the source code
Many reasons as, for example, the best practices and it better to keep maintained. 
- It still using of https://github.com/go-swagger/go-swagger 
- By go-swagger generate the YAML file from the source code
- The YAML file now is created/updated when the `make setup` is made. 
1. Clone the project locally
2. Remove the swagger.YAML file of the project
3. Run the make setup command and check if the swagger.YAML file was created automatically
```shell
$ make setup
Installing errcheck dependence:
go get -u github.com/kisielk/errcheck
Setting up Git hooks:
ln -sf $PWD/.githooks/* $PWD/.git/hooks/
Installing application dependencies:
dep ensure
make build_swagger_api
Installing …
```
> feat(swagger) : Generate swagger api from the source code (AEROGEAR-8518)

- ui/package-lock.json
- ui/package.json
- ui/src/configureStore.js
- ui/src/index.js
- ui/src/reducers/apps.js
Manage state better in UI (https://issues.jboss.org/browse/AEROGEAR-8527)
Use redux store to store and manage UI app state
Manage state more effectively and efficiently
Add redux lib, create single redux store, and add redux handlers and state to manage updates to app state
- Connect a component to the redux store & verify you are able to retrieve data from the store. For example, you can update `App.js` and check the console in your dev tools to verify the console.log prints row data:
```javascript
import React, { Component } from 'react';
import { connect } from 'react-redux';
class App extends Component {
render() {
console.log('rows', this.props.apps);
return (
<div className="App">
<p>Mobile Security Service</p>
</div>
);
}
}
const mapStateToProps = (state) => {
return {
apps: …
```
> Add redux to manage UI state

- pkg/httperrors/httperrors_test.go
https://issues.jboss.org/browse/AEROGEAR-8551
Deleted code that was commented out and unused.
This code was not needed and was left here by mistake.
> fix(unit-tests): Removed commented out code (AEROGEAR-8551)

- cmd/mobile-security-service/main.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/db/db.go
- pkg/models/device.go
- pkg/models/errors.go
- pkg/test/api_test.go
- pkg/test/fixtures.go
- pkg/web/apps/apps_http_handler.go
- pkg/web/middleware/middleware.go
- pkg/web/router/router.go
https://issues.jboss.org/browse/AEROGEAR-8569
Increased Go report card score from A to A+.
The Go report card score is an indication of the overall quality of the application. Increasing it to an A+ will improve public perception. It is currently at an [A](https://goreportcard.com/report/github.com/aerogear/mobile-security-service).
Installed the [Go Report Card CLI](https://github.com/gojp/goreportcard). Ran the CLI and updated code based on the CLI output.
To test this locally there are a few things you need to install.
Install Go Report Card CLI:
```sh
$ go get github.com/gojp/goreportcard
```
There are a few static analysis tools that Go Report card requires.
Install misspell:
```sh
$ go get -u github.com/client9/misspell/cmd/misspell
```
```sh
$ go get -u github.com/fzipp/gocyclo
``` …
> fix(go-report-card): Increase report card score to A+ (AEROGEAR-8569)

- pkg/test/api_test.go
- pkg/web/apps/apps_http_handler.go
- pkg/web/router/router.go
https://issues.jboss.org/browse/AEROGEAR-8557
Change handler implementation to be an interface
It will allow us to mock the handler to test it 
1. Check if the app still passing in the CI
2. Check if the router calls are as it was before ( check if the getAll still working )
> feat(handler) : Change handler implementation to be an interface

- README.adoc
https://issues.jboss.org/browse/AEROGEAR-8572
https://issues.jboss.org/browse/AEROGEAR-8570
- Add the steps to explain how to set up  and test the server locally
- Add the steps to explain how to use pgadmin and configure it
- Add the steps on how to check and test the REST Service API
- Doing many improvements in the doc
- Adding the steps to setup it locally without docker. 
Make easier to contribute and work with this project. 
Check the changes in the view mode of this PR. 
See: https://github.com/aerogear/mobile-security-service/blob/fb8f0a0e8dd77cc012ae994b37b90d5e9620f16b/README.adoc
- [] TODO
> feat(doc) : many improvements

- README.adoc
- ui/README.adoc
https://github.com/aerogear/mobile-security-service/pull/66
Improvements in the README in order to address the comments made in the merged PR 66
Check the changes in this PR in the view mode. 
Please, feel free to review all README. We can address other improvements as well. 
- [] TODO
> feat(doc) : Improvements in the README in order to address the comments made in the merged PR 66

- README.adoc
@camilamacedo86 This is a really small change to fix a broken link. Could you take a look when you have some time. No JIRA related to this as it's one character change.
> fix dep link

- pkg/helpers/fixtures.go
- pkg/web/apps/apps_http_handler.go
- pkg/web/apps/apps_http_handler_test.go
- pkg/web/apps/apps_psql_repository.go
- pkg/web/apps/apps_service_test.go
https://issues.jboss.org/browse/AEROGEAR-8749
Add fmt fixes that are being generated by the pre-commit hook
```
modified:   pkg/helpers/fixtures.go
modified:   pkg/web/apps/apps_http_handler.go
modified:   pkg/web/apps/apps_http_handler_test.go
modified:   pkg/web/apps/apps_psql_repository.go
modified:   pkg/web/apps/apps_service_test.go
```
Good practices and allow the others to use with success the git hooks
By using the git hook and the command go fmt to fix it
- Get this PR
- Execute the command `go fmt $(go list ./... | grep -v /vendor/)`
- It should return success and 0 files/lines.
> fix(fmt): Fix formatting issues discovered by pre-commit hook (AEROGEAR-8749)

- ui/package-lock.json
- ui/src/actions/actions-ui.js
- ui/src/actions/types.js
- ui/src/components/AppDetailedView.js
- ui/src/components/LandingPage.js
- ui/src/components/__tests__/Header.test.js
- ui/src/components/common/Header.css
- ui/src/components/common/Header.js
- ui/src/reducers/__tests__/index.test.js
- ui/src/reducers/index.js
Add header to landing page screen. AEROGEAR-8375
Header for landing page ui screen
header
Create header component with PF4 & add to Landing Page
- `npm start` 
- visually confirm header is rendered on landing page, and includes avatar icon, username, and dropdown with logout option
- verify dropdown toggles opens and closed
- verify dropdown closes after logout option selected
- run `npm test` & confirm all tests pass
> feat(UI): adds Header component

- .circleci/config.yml
- Makefile
- ui/README.adoc
- ui/package-lock.json
- ui/package.json
- ui/src/DataService.js
- ui/src/containers/__tests__/AppsTableContainer.test.js
- ui/src/reducers/__tests__/index.test.js
UI missing from CI config (AEROGEAR-8370)
Add CI build checks for react UI
Keep those frontend devs honest
Update CircleCI config and Makefile
Check CircleCI build details
> feat(CI): Add UI to Circle CI (AEROGEAR-8370)

- ui/README.adoc
- ui/package.json
https://issues.jboss.org/browse/AEROGEAR-8754
Add min node 1o to README 
Add engine to package.json
Fix on linting error
View the README works? - not much to do here really
> fix: add node engine and lint fix (AEROGEAR-8754)

- ui/src/reducers/__tests__/index.test.js
- ui/src/reducers/index.js
https://issues.jboss.org/browse/AEROGEAR-8769
Added an additional column and update tests
See JIRA
Add the column
1. Run db
2. Ensure entries in the db
3. Run `make serve`
4. Table should appear as below
5. Run `npm test`
6. Tests should pass
> fix: add additional column to apps table (AEROGEAR-8769)

- ui/src/actions/__tests__/actions-ui.test.js
- ui/src/actions/actions-ui.js
- ui/src/actions/types.js
- ui/src/components/AppDetailedView.js
- ui/src/components/AppsTable.js
- ui/src/components/LandingPage.css
- ui/src/components/LandingPage.js
- ui/src/components/Table.css
- ui/src/components/common/Header.js
- ui/src/containers/AppsTableContainer.js
- ui/src/containers/TableContainer.css
- ui/src/reducers/__tests__/index.test.js
- ui/src/reducers/index.js
https://issues.jboss.org/browse/AEROGEAR-8766
Styling
- The table
- I also improved the blank slate somewhat
It's nice when things look nice
css magic
1. Run `make serve`
2. UI should appear as below
Pushing this as a WIP as I'm basing it on the styling as outlined in the story flat but I did make some additions that weren't asked for so happy to remove those if necessary.
> fix(style): adding style to the apps detail table (AEROGEAR-8766)

- ui/package-lock.json
- ui/package.json
- ui/src/actions/__tests__/actions-ui.test.js
- ui/src/actions/actions-ui.js
- ui/src/actions/types.js
- ui/src/components/App.js
- ui/src/components/AppDetailedView.css
- ui/src/components/AppDetailedView.js
- ui/src/containers/AppDetailsContainer.js
- ui/src/containers/AppsTableContainer.js
- ui/src/containers/__tests__/AppDetailsContainer.test.js
- ui/src/reducers/__tests__/index.test.js
- ui/src/reducers/index.js
Implement an App Details view (AEROGEAR-8468)
Implement an App Details view
View details of an app
Implement components, wire up to redux, and add tests
```shell
npm test
npm start
Verify:
- table renders with sample data
- table sorts correctly
- no error output when verifying changes
- no warning output when verifying changes
```
> feat(UI): Adds App Detail view (AEROGEAR-8468)

- pkg/web/apps/apps_http_handler.go
- pkg/web/apps/apps_http_handler_test.go
- pkg/web/apps/apps_service.go
- pkg/web/apps/apps_service_mock.go
- pkg/web/apps/apps_service_test.go
https://issues.jboss.org/browse/AEROGEAR-8822
Add a check to validate if the versions are from the app sent. 
1. Check the CI.
2. Following the manual test:
a) Call the endpoint by sending versions which are NOT associated with the app informed (Should return an error)
b) Call the endpoint by sending versions which are associated with the app informed (Should work)
PS.: Check here how to call the endpoint: https://github.com/aerogear/mobile-security-service/pull/72
> feat(update-versions) : Add check to validate the app id of the versions sent

- ui/src/components/AppDetailedView.js
- ui/src/components/LandingPage.js
- ui/src/components/__tests__/Content.test.js
- ui/src/components/common/Content.js
- ui/src/containers/AppOverviewContainer.js
- ui/src/index.css
https://issues.jboss.org/browse/AEROGEAR-8874
Create a common UI content container using the Patternfly 4 Grid system.
To ensure the main application content lies within a consistent boundary.
[Patternfly 4 Grid](http://patternfly-react.surge.sh/patternfly-4/layouts/grid)
Verify that the width of the content in all views are the same.
> feat(ui): Create a common UI container using Patternfly 4 Grid (AEROGEAR-8874)

- ui/package-lock.json
- ui/package.json
- ui/src/containers/AppVersionsTableContainer.js
https://github.com/aerogear/standards/issues/AEROGEAR-8839
Format the date
Humans can't read. Also it'll contain the timezone
1. Render the page and view the date
> fix: format date (AEROGEAR-8839)

- .gitignore
- ui/src/actions/__tests__/actions-ui.test.js
- ui/src/components/AppsTable.js
- ui/src/components/__tests__/AppDetailsToolbar.test.js
- ui/src/components/__tests__/AppsTable.test.js
- ui/src/components/__tests__/Header.test.js
- ui/src/components/__tests__/LandingPage.test.js
- ui/src/components/__tests__/LargeModal.test.js
- ui/src/components/common/LargeModal.js
- ui/src/containers/__tests__/AppVersionsTableContainer.test.js
Expand ui test coverage & add test for landing page. https://issues.jboss.org/browse/AEROGEAR-8849, https://issues.jboss.org/browse/AEROGEAR-8860
Add tests
Increase test coverage
Add tests
Check all tests run in CI for UI
> feat(tests): expand UI test coverage

- ui/.eslintrc
- ui/package-lock.json
- ui/package.json
Adding react hooks eslint plugin and rules
To catch errors and warning for our react hooks
> feat(ui): Add react hooks eslint rules

- ui/src/components/Header.js
- ui/src/containers/HeaderContainer.js
https://issues.jboss.org/browse/AEROGEAR-9030
Log out functionality
Redirect the user to the /oauth/sign_in endpoint
1. Build the docker image locally
`docker build -t docker.io/aerogear/mobile-security-service:AEROGEAR-9030-verification .`
2. Push Image to dockerhub
`docker push docker.io/aerogear/mobile-security-service:AEROGEAR-9030-verifcation`
3. Deploy the image to the project in the community cluster
3a. Contact me for link to project
3b. Update the deployment config `image` to the new docker image
3c. Wait for the deployment to finish and the pod to come up.
4. Navigate to the mss route
5. You should be presented with the OAuth login screen. 
6. Log in
7. Click on the dropdown and choose logout.
8. You should be redirected to the OAuth login-in screen.
> feat(ui): oauth logout (AEROGAR-9030)

- ui/src/containers/AppsTableContainer.js
- ui/src/containers/AppsTableContainer.spec.js
- ui/src/containers/HeaderContainer.js
- ui/src/containers/HeaderContainer.spec.js
AEROGEAR-9040
Update container tests
UI code was refactored and now tests need to be updated
Create/ update test files for all UI containers
- check tests pass:
- verify in CI build for UI at bottom of this PR
- run `npm test` locally in the /ui folder
> Container tests

- ui/src/components/common/ConfirmationModal.js
- ui/src/components/common/Content.js
- ui/src/containers/AppsTableContainer.js
- ui/src/containers/HeaderContainer.js
- ui/src/containers/appView/AppPageContainer.js
- ui/src/containers/appView/AppVersionsTableContainer.js
- ui/src/containers/appView/DisableAppModalContainer.js
- ui/src/containers/appView/NavigationModalContainer.js
- ui/src/containers/appView/SaveAppModalContainer.js
Comment code
Add code comments
Improve code readability
Add comments to code
Verify comments in code are accurate
> fix(docs): adds container JSDoc comments

- pkg/models/app.go
https://issues.jboss.org/browse/AEROGEAR-8914
Create fun to create the object
Shows a good practice use the MSS model instead of replicated it in the operator project
Just add the new func for we are able to create the struct
> feat(app) : Add new for apps struct (AEROGEAR-8914)

- CHANGELOG.MD
https://issues.jboss.org/browse/AEROGEAR-9373
- Add Changelog with the info regards the release of the init version.
> feat(Release) : Add changelog

- CHANGELOG.MD
- README.adoc
https://issues.jboss.org/browse/AEROGEAR-9372
- Fix tag name in the CHANGELOG
- Add info to the README over how to do the releases
- Have this process doc
> feat(README) : Add info over how to do the releases (AEROGEAR-9372)

- CHANGELOG.MD
- api/swagger.yaml
- ui/package-lock.json
- ui/package.json
> feat: bump version to 0.2.0

- CHANGELOG.MD
- api/swagger.yaml
- cmd/mobile-security-service/main.go
- ui/package-lock.json
- ui/package.json
Updated lodash-es to fix a CVE.
https://github.com/lodash/lodash/pull/4336
> build(lodash-es): update dependency (AEROGEAR-1234)

- CHANGELOG.MD
- ui/package.json
> Release 0.2.2
